### ISSUE TITLE
V4: Cannot find module 'email-misspelled' or its corresponding type declarations.

### ISSUE THREAD

**Issue by limonte** [julien-amblard/email-misspelled#66]
Here's what I'm getting after upgrading from v3 to v4.1: 

![CleanShot 2024-03-17 at 10 49 32@2x](https://github.com/julien-amblard/email-misspelled/assets/6059356/fbc9b36b-5c65-42ea-9ee5-f32cdda5066b)

**Comment by julien-amblard** [comment]
Hello
Can you give me more detail on how to reproduce this issue ? 
Typescript version, tsconfig, node version, a repository maybe ?

Thank you

**Comment by limonte** [comment]
Hello @julien-amblard and thank you for the prompt reply!

I'm using webpack 5, here's the PR that fixes the issue for my project: #67 

Read more about the `types` field: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by felixgenicio** [comment]
This doesnt't solve the issue. 
I've tried in a clean folder:
```
mkdir test
npm i email-misspelled
vi test.js

#use test code
import emailMisspelled, { top100 } from "email-misspelled"
const emailChecker = emailMisspelled({ domains: top100 })
emailChecker("user@otmail.com")

node test.js

![Screenshot 2024-03-27 at 10 27 18](https://github.com/julien-amblard/email-misspelled/assets/44643166/b487625b-40eb-42f8-8600-4abe68441fb0)

**Comment by julien-amblard** [comment]
can you link me your tsconfig ?

**Comment by felixgenicio** [comment]
The error fires just with a simple test file, without a tsconfig. I want to use the library in a backend that also have no tsconfig file.

**Comment by julien-amblard** [comment]
OK I see, I will do something I was already planning to do: using sites as builder. It should solve your issue.
I'll do that asap

**Comment by limonte** [comment]
@felixgenicio this is a different issue from mine, please create another issue

**Comment by limonte** [comment]
You have to add `"type": "module"` to `package.json` to use `import` statement, that's probably the issue.

**Comment by julien-amblard** [comment]
still, could you share me a reproducible environment ?
